server:
  port: 8082
spring:
  application:
    name: seckill-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 150.158.156.214


management:
  endpoints:
    web:
      exposure:
        include: "*"
#服务的端点检查
#http://127.0.0.1:8082/actuator/nacos-discovery