server:
  port: 9090

spring:
  application:
    name: seckill_provider
  cloud:
    nacos:
      discovery:
        server-addr: 150.158.156.214
  datasource:
    url: jdbc:mysql://150.158.156.214:3306/seckill?characterEncoding=utf-8&useSSL=false
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 0
    host: 150.158.156.214
    port: 6379
    password: test123

